### ISSUE TITLE
mix error on heroku

### ISSUE THREAD

**Issue by hansbonini** [mirego/accent#112]
```-----> Apt app detected
-----> Updating apt caches
       Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
       Get:2 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease [46.3 kB]
       Get:3 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main amd64 Packages [260 kB]
       Get:4 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
       Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
       Get:6 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
       Get:7 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
       Get:8 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [730 kB]
       Get:9 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [597 kB]
       Get:10 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [905 kB]
       Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,255 kB]
       Fetched 16.9 MB in 3s (6,558 kB/s)
       Reading package lists...
-----> Fetching https://s3.amazonaws.com/shared.ws.mirego.com/libyaml-dev_0.1.4-3ubuntu3-2.1_amd64.deb
-----> Installing libyaml-dev_0.1.4-3ubuntu3-2.1_amd64.deb
-----> Writing profile script
-----> Elixir app detected
-----> Checking Erlang and Elixir versions
       Will use the following versions:
       * Stack heroku-18
       * Erlang 21.2
       * Elixir 1.8.1 
-----> Will export the following config vars:
API_HOST
API_WS_HOST
DATABASE_URL
FORCE_SSL
GOOGLE_API_CLIENT_ID
GOOGLE_API_CLIENT_SECRET
MIX_ENV
RESTRICTED_DOMAIN
WEBAPP_URL
       * MIX_ENV=prod
-----> Stack changed, will rebuild
-----> Fetching Erlang 21.2 from https://s3.amazonaws.com/heroku-buildpack-elixir/erlang/cedar-14/OTP-21.2.tar.gz
-----> Installing Erlang 21.2 (changed)
-----> Fetching Elixir v1.8.1 for OTP 21 from https://repo.hex.pm/builds/elixir/v1.8.1-otp-21.zip
-----> Installing Elixir v1.8.1 (changed)
-----> Installing Hex
* creating /app/.mix/archives/hex-0.20.1
-----> Installing rebar
* creating /app/.mix/rebar
* creating /app/.mix/rebar3
-----> Fetching app dependencies with mix
** (CompileError) config/config.exs:1: module Config is not loaded and could not be found
    (elixir) lib/code.ex:232: Code.eval_string/3
    (mix) lib/mix/config.ex:220: Mix.Config.eval!/2
 !     Push rejected, failed to compile Elixir app.
 !     Push failed ```

**Comment by gcauchon** [comment]
The project was recently updated to `v1.9`, which changed the way configuration are handled. The buildpack still tries to "build" using `v1.8.1`, thus the error:

> module Config is not loaded and could not be found

I strongly recommend deploying the OTP release image to Heroku instead of the buildpack/`mix phx.server` former setup. We should probably update the readme to follow this recommendation. A `make` target is even available to easily build the image, then follow the steps documented in Heroku : to  and "release" the image.

### 1. Build the image

```shell
> make build
```

### 2. `tag`, `push` the image to Heroku’s registry

https://devcenter.heroku.com/articles/container-registry-and-runtime#pushing-an-existing-image

### 3. Release the image as a new app version

https://devcenter.heroku.com/articles/container-registry-and-runtime#releasing-an-image

**Comment by hansbonini** [comment]
Thanks!

**Comment by simonprev** [comment]
@tomsiwik I updated the buildpack to 1.9.1 but I did not tested it, but it can’t be worse than the 1.8 version that could not compile the projet 😃

**Comment by tomsiwik** [comment]
@simonprev wow. much appreciated... that was quick help. I'll try it out.

**Comment by tomsiwik** [comment]
Well... still doesn't work. No error in the build though (only warnings). The release just fails without knowing why.

**Comment by simonprev** [comment]
> The release just fails without knowing why.

Did you provide a `DATABASE_URL` in the settings? The first step before the release is made available is the database migration.

Do you have a stacktrace?

**Comment by tomsiwik** [comment]
This was the heroku button configuration. There was no DATABASE_URL to setup as it was already attached. I can't get the stacktrace from the button. It fails silently and sais please check your configuration above.

**Comment by tomsiwik** [comment]
I managed to get the trace. 

<dl>
<dt>Release error</dt>
<dd>

```
20:30:09.053 [error] GenServer #PID<0.287.0> terminating
** (RuntimeError) connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (elixir) lib/keyword.ex:393: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:92: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

20:30:09.053 [error] GenServer #PID<0.286.0> terminating
** (RuntimeError) connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (elixir) lib/keyword.ex:393: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:92: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

20:30:09.056 [error] GenServer #PID<0.288.0> terminating
** (RuntimeError) connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (elixir) lib/keyword.ex:393: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:92: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

20:30:09.057 [error] GenServer #PID<0.289.0> terminating
** (RuntimeError) connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (elixir) lib/keyword.ex:393: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:92: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

20:30:09.057 [error] GenServer #PID<0.290.0> terminating
** (RuntimeError) connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (elixir) lib/keyword.ex:393: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:92: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (EXIT from #PID<0.92.0>) shutdown
```
</dd>

</dl>

**Comment by simonprev** [comment]
What do you mean by _Got it to work: MIX_ENV: releases was the solution_? You replaced `MIX_ENV` from `prod` to `releases`?

> Seems to be indeed the database. How do I set it when using the heroku-button? Isn't it attached and the default is DATABASE_URL in heroku? I'm confused now.

The `DATABASE_URL` should be added to the created app automatically: https://github.com/mirego/accent/blob/master/app.json#L54

The steps to deploy on Heroku with the Heroku button:

- Fill in the required variable
- Click on Deploy
- Heroku will spawn the app with a DATABASE_URL config, to see the app you can go to the Heroku web dashboard or use the CLI: `heroku config --app your-app-name
- Use this DATABASE_URL config to connect to the database your a postgresql client (postico, tableplus, pgadmin, psql…)
- Execute the following query: CREATE EXTENSION pg_trgm

This issue seems to describe your problem: https://github.com/mirego/accent/issues/109#issuecomment-515018208

For the `Poison` issue, I just saw that the `mix.lock` file had some unused dependencies (like `Poison`). Maybe it is related to `MIX_ENV: releases` 🤔 

I will fix the unused deps when I have time to work on this project 👍

**Comment by tomsiwik** [comment]
Well I had to adjust a few things here to successfully deploy the app on heroku, hence the fork: https://github.com/tomsiwik/accent

In the order that I had to adjust to make it work

1. Change from `MIX_ENV: prod` to `MIX_ENV: releases`, otherwise for some reason the env variable is not read. `DATABASE_URL` exists when running `heroku config` when the app is building. However the migration will never start as it won't be connected to the db. `releases` sets the variable... and that seems to be the issue.

2. Heroku is missing trigram extension and superuser, the first steps after migrations will fail:
https://github.com/mirego/accent/blob/master/priv/repo/migrations/20180426090527_add_trigram_indices_on_searchable_fields.exs#L7

3. Poison error happens after successful deployment when using google auth provider. Might be because of `MIX_ENV: releases`, I don't really know, not an elixir guy here. Adding the following removed the error:
https://github.com/tomsiwik/accent/blob/master/mix.exs#L78

4.  Github provider seems to get the wrong scope and errors out when you accept the oauth request. Adding `default_scope` solved that:
https://github.com/tomsiwik/accent/blob/master/config/releases.exs#L21

5. Tests aren't correct (in my fork) after I have upgraded packages (uberauth mainly) but this might be my fault. But they seem to be unrelated to the providers and something is translated wrongly. Not an issue, might be my own fault... but maybe double check.

With my own fork it works for now. Is there a way to make the deploy to heroku button tag based? Older versions don't seem to deploy either.

**Comment by machty** [comment]
@tomsiwik thank you so much for digging into this. I followed your steps and was able to at least get something deployed.

Note that I also had to add `check_origin: false` to releases.exs

```
config :accent, Accent.Endpoint,
  http: [port: System.get_env("PORT") || "4000"],
  check_origin: false
```

**Comment by simonprev** [comment]
@tomsiwik The last commits on `master` branch fix the issues you mentionned

1. _Change from MIX_ENV: prod to MIX_ENV: releases_ This was a missing line in the prod config. By using `releases` as `MIX_ENV`, the right file was loaded, but the `check_origin: false` in the config was not loaded.

2. I tested the Deploy with Heroku button and everything works fine without messing around with pg extension. The migration should run fine on the Heroku PG addon.

3. This was fixed in a release of uberauth

4. I added the right `default_scope` for GitHub.

5. Test are working locally, make sure to run `npm run build-production-inline --prefix webapp` because we test that the Phoenix `WebappController` renders the EmberJs app 😄 The GitHub Actions workflow should be fixed soon (once we fix our billing for the feature)

Thank you for the report! 😃
