### ISSUE TITLE
docker-compose deployment doesn't work with Dockerfile

### ISSUE THREAD

**Issue by dmitry** [mirego/accent#121]
When building from `docker-compose` the `Dockerfile` it raises an error:

```
Step 38/44 : RUN mv /opt/$APP_NAME/webapp-dist /opt/$APP_NAME/lib/$APP_NAME-$APP_VERSION/priv/static/webapp &&     mv /opt/$APP_NAME/jipt-dist /opt/$APP_NAME/lib/$APP_NAME-$APP_VERSION/priv/static/jipt
 ---> Running in 2c9ae72a733e
mv: can't rename '/opt//webapp-dist': No such file or directory
ERROR: Service 'application' failed to build: The command '/bin/sh -c mv /opt/$APP_NAME/webapp-dist /opt/$APP_NAME/lib/$APP_NAME-$APP_VERSION/priv/static/webapp &&     mv /opt/$APP_NAME/jipt-dist /opt/$APP_NAME/lib/$APP_NAME-$APP_VERSION/priv/static/jipt' returned a non-zero code: 1
```

Image build works fine.

**Comment by tomsiwik** [comment]
I have the same issue for month... $APP_NAME is never set. Running docker hub images seems fine. but a simple `make`, I have tried 2 month before and today it's still does not working. Pushing to heroku with this is also not possible because of #112. It's a cool tool... I like it, but the ease of use for the first setup seems unpleasant yet. Still a big thumbs up to keep it going.

**Comment by simonprev** [comment]
I refactored the `Dockerfile` to not take the `APP_NAME` but it still needs a `APP_VERSION` variable. The task to use the docker-compose build is `make compose-build`.

> Pushing to heroku with this is also not possible because of #112

I did not fix the probleme with heroku because I had no time to test it. But all of our Accent instance run fine on Heroku with the container release! https://devcenter.heroku.com/articles/container-registry-and-runtime
