### ISSUE TITLE
Support Add / Remove / Modify string from UI

### ISSUE THREAD

**Issue by hedin-hiervard** [mirego/accent#222]
It's a Feature Request.

Currently it's only possible to modify the string list with a sync. It would be nice to have an interface to do so from the web part.
Any action with a string makes all translations pending review.

**Comment by simonprev** [comment]
Since the flow is "developer oriented", we need to push the string first and then pull the changes from Accent. If we can add strings in the UI, the next push from the developer will remove those newly added strings since they will not be present in the pushed document.

Do you have a different workflow that would make adding strings in the UI work?

**Comment by hedin-hiervard** [comment]
No, I'm using fully automated workflow. However, I have to export first, then parse PO file, then add my terms and sync it back. How easier it would be to just call `/add-term` or `/remove-term` on the API?

**Comment by simonprev** [comment]
After careful consideration (3 years), we have decided not to implement this kind of workflow at this time, but we appreciate your input!
