### ISSUE TITLE
How to use curl with API endpoints?

### ISSUE THREAD

**Issue by chokokatana** [mirego/accent#256]
I'm trying to undestand [the documentation regarding endpoints](https://www.accent.reviews/guides/api-endpoints.html#export) but nothing I do seems to work. When I run something like `curl "https://domain/export/?project_id=project-uuid&language=en&document_format=strings&document_path=Localization"` I only get "Not found" errors.

When I try to run a GraphQL client against the domain and fetch the schema I get 404.

**Comment by chokokatana** [comment]
Using as example a demo project created at http://demo.accent.reviews/app/projects/7189c5d1-5853-4e7c-a7a1-b39d4b20977e I try to run:

> curl "http://demo.accent.reviews/export/?project_id=7189c5d1-5853-4e7c-a7a1-b39d4b20977e&language=en&document_format=strings&document_path=Localization"

**Comment by simonprev** [comment]
Hi @chokokatana thanks for trying out Accent! You get a 404 because your `document_path` is not found. I see in your project that your uploaded file has the name `strings`.

<img width="917" alt="image" src="https://user-images.githubusercontent.com/464900/121020577-7e0c5700-c76e-11eb-93ca-876fd4e5ec78.png">

So this command, with your API token should yield the correct result:

> curl "http://demo.accent.reviews/export/?project_id=7189c5d1-5853-4e7c-a7a1-b39d4b20977e&language=en&document_format=strings&document_path=strings"

The `document_format` params is the file serializer that will be used. Your uploaded default was `android_xml` but you can export it for any other format.

Cheers!
