### ISSUE TITLE
Correct feature branch handling with overriding translations

### ISSUE THREAD

**Issue by ChiefORZ** [mirego/accent#360]
Please help me, i don't know how to handle "staging" environments.

For explanation, we only have the master language file (en.json) committed in our repository, in the build step the accent cli syncs all localised translations.
When working on a new feature where a lot of translations change (e.g. will be updated or even removed) we do this on a feature branch. The problem is now, `accent sync` will override the changes to the translations even for the running main branch - and therefore keys will be deleted.

In our situation, we think following options are needed:
- Either allow a option for `accent sync` to be additive, meaning no translations will be deleted on sync, you just have to make sure to create new translation keys when you edit a already existing to keep the main branch functioning.
- Allow the creation of versions on the fly. When a feature branch is created, you should be able to create a new version revision and sync your changes in this new version. As well as merge translations made back into the main branch and deleting it via cli.

We are curious how others are tackling this similar issue with accent, maybe someone could give as a hint. There should probably be a guide in the official docs.

Thanks ✌️

**Comment by simonprev** [comment]
> We are curious how others are tackling this similar issue with accent

Since we are (@mirego) the main users for the app, I can explain our workflow:

- The "main" branch is the one that syncs to Accent, with a GitHub Actions workflow.
- The feature branch are not synced since there is no need to translate/review before it hits the main branch
- When we do a "release", we create it in Accent web UI
- Then, using a new-ish feature from the CLI, syncing in a `release/v*` branch syncs the correct version in Accent
- What is then officially reviewed and "stamped" is the version.
- Then we release the app 🎉 

Conflicts between versions and merge are handled by our Git workflow and not our Accent workflow.

We have in our roadmap the "automatic" part of creating version from the CLI 😄
