### ISSUE TITLE
IDEA: Own tab for translators

### ISSUE THREAD

**Issue by RappyTV** [mirego/accent#401]
# A little addition to #393.
### States
+ `Initial` - When a string is created
+ `Translated` - Translated but not applied to translation files
+ `Reviewed` - Translated & reviewed and applied to translation files

If a translator translates a string it's put in the `Translated` state.
If a Reviewer reviews a string it's put in the `Reviewed` state.

My Idea would be to have an extra tab exclusively for translators (and admins obviously) looking like the tab for the reviewers showing strings that are in the `Initial` state. So translators also have the possibility to translate strings inline and not having to switch to a new tab for every string they want to translate.
Already translated or reviewed strings can be changed in the All strings tab.

It would also be great to add a new filter option for the Review tab to only show strings in the `Translated` state which hide strings in the `Initial` (and `Reviewed` ofc) state, so they can review strings which are translated by a translator so you only see string which really have to be reviewed.

**Comment by simonprev** [comment]
That’s a good idea! I modified the sidebar so that the translator role have a "Translate" item that links to the new "Review" page. The page has been improved to show all languages side by side. It has filters and state color for "translated", "reviewed".

<img width="1245" alt="image" src="https://github.com/mirego/accent/assets/464900/29b3ea2d-574c-4266-b229-90bc18b8ae04">

You can open another issue if the new page is missing something 😄
