### ISSUE TITLE
JIPT invalid link

### ISSUE THREAD

**Issue by jfcartkeep** [mirego/accent#405]
Hi,

Is the just in place translations is still a supported feature in Accent? The link [here](https://github.com/mirego/accent/blob/33e77726dbf70eb891829d5cdde03540ec660049/webapp/app/pods/components/project-settings/jipt/template.hbs#L8) is not valid anymore and I can't seem to find it on https://www.accent.reviews/guides/.

Thanks!

**Comment by simonprev** [comment]
Hi Jeff! I want to support it but it’s not used internally at Mirego 😬 If you want to use the feature and report issues I will be glad to accept fixes 😄 

Since the guide has been removed (when migrating off the old Gatsby static site), I can explain the feature:

Basically the goal is to add a new "pseudo-language" that the content will be picked up by the JIPT script. (I found old screenshots of the guides)

<img width="802" alt="image" src="https://github.com/mirego/accent/assets/464900/b164a527-269a-48f8-920c-f522702e1fa7">

Now when you include the script, you should be able to interact with the embedded iframe and modify the content in place.

<img width="798" alt="image" src="https://github.com/mirego/accent/assets/464900/d4e1a80c-0743-4761-b011-44aad454e911">

Hope that helps!

**Comment by simonprev** [comment]
Hey Jeff, I just fixed the script 🎉 

I also added an example page from the settings "jipt" page:

<img width="1128" alt="image" src="https://github.com/mirego/accent/assets/464900/fd72bf8e-aebb-41af-b247-3f841d0a0a94">
