### ISSUE TITLE
Google OAuth does not work

### ISSUE THREAD

**Issue by l0nax** [mirego/accent#48]
I have deployed the App with [heroku.com](heroku.com).
The Variable `GOOGLE_API_CLIENT_ID` was set!!!
<br>
When i now go to the [Heroku Website](https://l0naxac.herokuapp.com/) and i click on the Button `Login with Google` it opens a Popup from Google, and after i putted in my Creditals and the Google Window Closes.
But it still shows the "Login Screen" of Accent.

**Comment by l0nax** [comment]
In Firefox are no Addons Active (and it was installed three hours earlier).
And it also does not work with Chrome.

**Comment by simonprev** [comment]
Does the JavaScript console prints an error? `popup_closed` or something like that?

**Comment by l0nax** [comment]
No it does not print anything on the Chrome/Firefox console

Simon Prévost <notifications@github.com> schrieb am Do., 21. Juni 2018,
18:45:

**Comment by l0nax** [comment]
Will I receive an Answer or will be this Issue let opened and nothing will be done?

**Comment by simonprev** [comment]
Since this does not have any debugging information I suggest you to include a screencast of your browser reproducing your issue. This will make it easier for me to spot a configuration or a behavior that is linked to your issue.

**Potential issues:**
- Browser compatibility
- Addons
- Misconfiguration of your Google App
- Misconfiguration of the API
- Misconfiguration of the Ember app

**Comment by l0nax** [comment]
The Problem has been solved from alone :/

I don't have done anything
I have only retried it on Heroku and now it works??!!

**Comment by simonprev** [comment]
Ah perfect 👍 It can take a while for the configuration of a Google App to "spread" so it might have been the cause of your issue.
