### ISSUE TITLE
Support an alternative to Google Auth

### ISSUE THREAD

**Issue by Mokou** [mirego/accent#80]
Whether it’s just a simple username & password method, or support for more OAuth providers, it would be nice to be able to use this software without also having to use Google.

**Comment by simonprev** [comment]
Fixed with the new login screen and https://github.com/ueberauth/ueberauth integration from this commit: https://github.com/mirego/accent/commit/768a2fac3ecf4bdcab792084d5904b473232bf41

It should now be trivial to add another service:
- Add strategy
- Add UI
- 💥 

**💅 What it looks like now if you configure every services available**
<img src="https://user-images.githubusercontent.com/464900/58274818-b09eaf00-7d61-11e9-9793-26e0cfa66dea.png" width=400 />

The simple username/password is not included because we would need to implement other features such as _forgot password_, _reset password email_, etc
