### ISSUE TITLE
Problem with parsing jitp value

### ISSUE THREAD

**Issue by LostKobrakai** [mirego/accent#84]
`{^You're an admin of this tenant. You can edit global settings in the admin area:@default}`
This doesn't seem to be picked up by the javascript.

**Comment by LostKobrakai** [comment]
I'm wondering if it wouldn't make more sense for the jipt to use uuids instead of the raw text string. This would for example also prevent string substitutions from changing the content of the jipt tag.

**Comment by simonprev** [comment]
I just tested it in my sample app and the key works:

![image](https://user-images.githubusercontent.com/464900/59634312-7df79480-911c-11e9-8eb0-9fe26029b239.png)

The regex used in JavaScript is `/{\^(.+)}/` so it should pickup any characters.

Could you provide more details on the translation row or the HTML that does not get picked up? Maybe it’s because of some HTML tags 🤔

> I'm wondering if it wouldn't make more sense for the jipt to use uuids instead of the raw text string

I wrote a big response but it just occurred to me that I could have used the UUID of the translation in the master language! The only advantage of using raw string is that before the script take over the Element Nodes, you see your text instead of cryptic UUID.

Anyway it should work with raw string on all cases. We just need to find how my example differ from yours 😄
